apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-ui
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - image: provectuslabs/kafka-ui:latest
          name: kafka-ui
          ports:
            - containerPort: 8086
          env:
            - name: KAFKA_CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_CLUSTER_NAME
                  name: kafka-ui-config
            - name: KAFKA_CLUSTER_BOOTSTRAPSERVERS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_CLUSTER_BOOTSTRAPSERVERS
                  name: kafka-ui-config
            - name: DYNAMIC_CONFIG_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: DYNAMIC_CONFIG_ENABLED
                  name: kafka-ui-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-ui
  name: kafka-ui
spec:
  ports:
    - name: kafka-ui
      port: 8086
      protocol: TCP
      targetPort: 8086
  selector:
    app: kafka-ui
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-config
data:
  KAFKA_CLUSTER_NAME: "local"
  KAFKA_CLUSTER_BOOTSTRAPSERVERS: "broker:29092"
  DYNAMIC_CONFIG_ENABLED: 'true'