apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak-mysql
  name: keycloak-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-mysql
  template:
    metadata:
      labels:
        app: keycloak-mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql_root_password
                  name: keycloak-mysql-secrets
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: keycloak-mysql-config
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: keycloak-mysql-config
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql_password
                  name: keycloak-mysql-secrets
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: keycloak-mysql-data
      volumes:
        - name: keycloak-mysql-data
          persistentVolumeClaim:
            claimName: keycloak-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak-mysql
  name: keycloak-mysql
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: keycloak-mysql
---
apiVersion: v1
data:
  mysql_password: bXlzcWw=
  mysql_root_password: cm9vdA==
kind: Secret
metadata:
  name: keycloak-mysql-secrets
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-mysql-config
data:
  MYSQL_DATABASE: "keycloak"
  MYSQL_USER: "keycloak"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-mysql-pv
spec:
  storageClassName: 'standard'
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/keycloak/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


