apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - image: prom/prometheus:v2.46.0
          name: prometheus
          ports:
            - containerPort: 9090
          args:
            - --enable-feature=exemplar-storage
            - --config.file=/etc/prometheus/prometheus.yml
          volumeMounts:
            - mountPath: prometheus-config
              name: /etc/prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  ports:
    - name: 9090-9090
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 2s
      evaluation_interval: 2s
    
    scrape_configs:
      - job_name: 'property-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'property-service.default.svc.cluster.local:8080' ]
            labels:
              application: 'Property Service'
      - job_name: 'notification-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'notification-service.default.svc.cluster.local:8083' ]
            labels:
              application: 'Notification Service'
      - job_name: 'image-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'image-service.default.svc.cluster.local:8082' ]
            labels:
              application: 'Image Service'
      - job_name: 'booking-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'booking-service.default.svc.cluster.local:8081' ]
            labels:
              application: 'Booking Service'
      - job_name: 'api-gateway'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'api-gateway.default.svc.cluster.local:9000' ]
            labels:
              application: 'Api Gateway'
