apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: booking-service
  name: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - image: alexpoty/estatein-booking-service
          name: estatein-booking-service
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: booking-service-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: booking-service
  name: booking-service
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: booking-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.default.svc.cluster.local:3306/booking_service"


