name: Build and publish frontend

on:
  push:
    branches:
      - "feature/set-up-frontend"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: alexpoty
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Build docker image
        working-directory: ./frontend
        run: |
          docker login --username alexpoty --password ${{secrets.DOCKER_TOKEN}}
          docker build -t estatein-frontend
          docker tag estatein-frontend:latest alexpoty/estatein-frontend:latest
          docker push alexpoty/estatein-frontend:latest