name: Build and publish frontend

on:
  push:
    branches:
      - "feature/set-up-frontend"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: alexpoty
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context:
          push: true
          tags: alexpoty/estatein-frontend:latest
