name: Application Test

on:
  pull_request:
    branches: ["develop", "master"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Set up Jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'
      - name: Set up env
        env:
          CLOUDINARY_URL: ${{secrets.CLOUDINARY_URL}}
      - name: Test with Maven
        run: mvn -B test