name: Application Test

on:
  push:
    branches: ["feature/github-ci-cd"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - uses: actions/checkout@v4
      - name: Set up Jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B test